### ISSUE TITLE
Docs - for text area react - onchange function will give me error message

### ISSUE THREAD

**Issue by lizhuomeng71** [GovAlta/ui-components-docs#204]
on this page, https://design.alberta.ca/components/text-area#tab-0

if I copy this function

onChange(name: string, value: string) {
  setValue(value);
}

I will get an build error

  x Expected ',', got ':'
    ,-[C:/dev/GOA/ui-components/playground/react/src/app/Textarea.tsx:5:1]
  5 |   // Initialize state with useState hook
  6 |   const [value, setValue] = useState<string>("");
  7 |
  8 |   onChange(name: string, value: string) {
    :                ^
  9 |     setValue(value);
 10 |   }
 10 |
    `----

![image](https://github.com/user-attachments/assets/58698f3a-4f37-4bf2-a680-15fbe5874fc3)

**Comment by ArakTaiRoth** [comment]
Closing issue as I can't delete, the code issue is duplicated where it needs to be in the ui-components repo
